# Importing the packages

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

# Importing the data

In [3]:
raw_data_np = np.genfromtxt("loan-data.csv",delimiter=";",skip_header=True,autostrip=True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

# Chceking for incomplete data

In [4]:
np.isnan(raw_data_np).sum()

88005

In [5]:
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np,axis=0)

C:\Users\Aksh Mehta\AppData\Local\Temp\ipykernel_25688\3953962029.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np,axis=0)


In [6]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temporary_stats = np.array([np.nanmin(raw_data_np,axis=0),temporary_mean,np.nanmax(raw_data_np,axis=0)])

C:\Users\Aksh Mehta\AppData\Local\Temp\ipykernel_25688\3294397240.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np,axis=0),temporary_mean,np.nanmax(raw_data_np,axis=0)])


In [8]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

# Splitting the dataset

# splitting the columns of numeric data and text data

# To get the indices of the column that only contains strings and argwhere check whether the values are different than zero

In [9]:
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()

In [10]:
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

# To get the indices of the column that only contains integers and argwhere check whether the values are different than zero

In [11]:
column_integers = np.argwhere(np.isnan(temporary_mean) == False).squeeze()

In [12]:
column_integers

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

# Re-importing the dataset

In [13]:
loan_data_strings = np.genfromtxt("loan-data.csv",delimiter=";",skip_header=1,autostrip=True,usecols = column_strings, dtype = np.str)
loan_data_strings

C:\Users\Aksh Mehta\AppData\Local\Temp\ipykernel_25688\928929677.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_strings = np.genfromtxt("loan-data.csv",delimiter=";",skip_header=1,autostrip=True,usecols = column_strings, dtype = np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [14]:
loan_data_numeric = np.genfromtxt("loan-data.csv",delimiter=";",skip_header=True,autostrip=True,usecols = column_integers, dtype = np.int,filling_values = temporary_fill)
loan_data_numeric

C:\Users\Aksh Mehta\AppData\Local\Temp\ipykernel_25688\520101001.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_numeric = np.genfromtxt("loan-data.csv",delimiter=";",skip_header=True,autostrip=True,usecols = column_integers, dtype = np.int,filling_values = temporary_fill)


array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616520,      938,     4679],
       [59432726,    15000,    15000, 68616520,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616520, 68616520,     2185],
       [46154151, 68616520,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616520,      309,      301]])

# The Name of the columns

In [15]:
header_full_strings = np.genfromtxt("loan-data.csv",delimiter=";",skip_footer=raw_data_np.shape[0],autostrip=True, dtype = np.str)
header_full_strings

C:\Users\Aksh Mehta\AppData\Local\Temp\ipykernel_25688\2593420701.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  header_full_strings = np.genfromtxt("loan-data.csv",delimiter=";",skip_footer=raw_data_np.shape[0],autostrip=True, dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [16]:
header_strings,header_numeric = header_full_strings[column_strings],header_full_strings[column_integers]

In [17]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [18]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Creating Checkpoints

#  Checkpoints are Places throughout our code where we store the copy of our dataset

In [19]:
def checkpoint(file_name,checkpoint_header,checkpoint_data):
    np.savez(file_name,header=checkpoint_header,data=checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return (checkpoint_variable)

In [20]:
checkpoint_test = checkpoint("checkpoint-test",header_strings,loan_data_strings)

In [21]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [22]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [23]:
np.array_equal(checkpoint_test['data'],loan_data_strings)

True

In [24]:
np.array_equal(checkpoint_test['header'],header_strings)

True

# Manipulating string columns

In [25]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [26]:
header_strings[0] = "issue_date"

In [27]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [28]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

# Issue Date(change the name to months to numbers)

In [29]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

# To remove -15 we will use the strip method

In [30]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0],"-15")

In [31]:
loan_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [32]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

# Now to replace the values for jan,feb... to 1,2.... we will use np.where function

In [33]:
months = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [34]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                     i,
                                     loan_data_strings[:,0])

In [35]:
loan_data_strings[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

In [36]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

# Loan Status

In [37]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [38]:
loan_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [39]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [40]:
np.unique(loan_data_strings[:,1]).size

9

# Seggregate the values as per good customer and bad customer with 0 and 1

In [41]:
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])
status_bad

array(['', 'Charged Off', 'Default', 'Late (31-120 days)'], dtype='<U18')

In [42]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)

In [43]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

# Term

In [44]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [45]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

# Strip the value months from the term column

In [46]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2]," months")

In [47]:
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [48]:
header_strings[2] = "term_months"

# Now we will replace the missing values with 60(term) as we will assume the worst

In [49]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                 '60',
                                  loan_data_strings[:,2])

In [50]:
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [51]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

# Grade and Sub grade

In [52]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [53]:
loan_data_strings[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [54]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [55]:
loan_data_strings[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [56]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

# Replace the empty values in sub grade with worst case scenario as per the grade of that column

In [57]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                        i + '5',
                                       loan_data_strings[:,4])

In [58]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

# Return the counts of value repeated which shows there are 9 postions where both grade and subgrade have empty data

In [59]:
np.unique(loan_data_strings[:,4],return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [60]:
loan_data_strings.shape

(10000, 8)

# As there are only 9/10000 positions where grade and sub-grade both are empty we can replace these values with some other grade (i.e. 'H1') as the count is negligible

In [61]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [62]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == ''),
                                        'H1',
                                       loan_data_strings[:,4])

In [63]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

# As we have replaced the necessary values in grade we can remove it

In [64]:
loan_data_strings = np.delete(loan_data_strings,3,axis=1)

In [65]:
loan_data_strings

array([['5', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [66]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [67]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [68]:
header_strings = np.delete(header_strings,3)

In [69]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [70]:
header_strings[3]

'sub_grade'

# Converting sub grade values to numbers

In [71]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [72]:
keys = list(np.unique(loan_data_strings[:,3]))

In [73]:
keys

['A1',
 'A2',
 'A3',
 'A4',
 'A5',
 'B1',
 'B2',
 'B3',
 'B4',
 'B5',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'D1',
 'D2',
 'D3',
 'D4',
 'D5',
 'E1',
 'E2',
 'E3',
 'E4',
 'E5',
 'F1',
 'F2',
 'F3',
 'F4',
 'F5',
 'G1',
 'G2',
 'G3',
 'G4',
 'G5',
 'H1']

In [74]:
values = list(range(1,np.unique(loan_data_strings[:,3]).shape[0] + 1))

In [75]:
values

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36]

In [76]:
dict_sub_grade = dict(zip(keys,values))

In [77]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [78]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i,
                                      dict_sub_grade[i],
                                      loan_data_strings[:,3])

In [79]:
loan_data_strings[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69')

In [80]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [81]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [82]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Verification Status

# Replace the values with 0's and 1's

In [83]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [84]:
loan_data_strings[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [85]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [86]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'),0,1)

In [87]:
loan_data_strings[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

In [88]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

# URLS

In [89]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [90]:
np.unique(loan_data_strings[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [91]:
np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [92]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [93]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [94]:
header_full_strings

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [95]:
loan_data_numeric[:,0].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [96]:
loan_data_strings[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [97]:
np.array_equal(loan_data_numeric[:,0].astype(dtype=np.int32),loan_data_strings[:,5].astype(dtype=np.int32))

True

# Remove the url column as it is no more different than id column in loan_data_numeric

In [98]:
loan_data_strings = np.delete(loan_data_strings,5,axis = 1)

In [99]:
header_strings = np.delete(header_strings,5)

In [100]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [101]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [102]:
loan_data_numeric[:,0]

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [103]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# State Address

In [104]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [105]:
raw_data_np.shape

(10000, 14)

In [106]:
loan_data_strings.shape

(10000, 6)

In [107]:
header_strings[5] = "state_address"

In [108]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [109]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [110]:
np.unique(loan_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [111]:
np.unique(loan_data_strings[:,5],return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

# Sort the states name and count according to descending order

In [112]:
states_name,states_count = np.unique(loan_data_strings[:,5],return_counts=True)

In [113]:
states_count_sorted = np.argsort(-states_count)

In [114]:
states_name[states_count_sorted],states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [115]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '',0,loan_data_strings[:,5])

In [116]:
loan_data_strings[:,5] 

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [117]:
np.unique(loan_data_strings[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [118]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [119]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_east), 4, loan_data_strings[:,5])

In [120]:
loan_data_strings[:,5]

array(['1', '4', '4', ..., '1', '3', '3'], dtype='<U69')

In [121]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

# Converting to numbers

In [122]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [123]:
loan_data_strings = loan_data_strings.astype(np.int)

C:\Users\Aksh Mehta\AppData\Local\Temp\ipykernel_25688\3786620335.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_strings = loan_data_strings.astype(np.int)


In [124]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

# Checkpoint1 : Strings

In [125]:
checkpoint_strings = checkpoint("Checkpoint-Strings",header_strings,loan_data_strings)

In [126]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [127]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [128]:
np.array_equal(checkpoint_strings["data"],loan_data_strings)

True

In [129]:
np.array_equal(checkpoint_strings["header"],header_strings)

True

# Manipulating numeric columns

In [130]:
loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616520,      938,     4679],
       [59432726,    15000,    15000, 68616520,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616520, 68616520,     2185],
       [46154151, 68616520,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616520,      309,      301]])

In [131]:
np.isnan(loan_data_numeric).sum()

0

# Substitute filler values

In [132]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# ID(By chceking whether the no of temporary_fill values we get to know the total no of nan values)

In [133]:
temporary_fill

68616520.0

In [134]:
np.isin(loan_data_numeric[:,0],temporary_fill)

array([False, False, False, ..., False, False, False])

In [135]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()

0

In [136]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# Temporary_stats

In [137]:
temporary_stats 

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [138]:
temporary_stats[:,column_integers]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

# Funded amount(The temporary fill values are replaced with the min values)

In [139]:
loan_data_numeric[:,2]

array([35000, 30000, 15000, ..., 10000, 10000, 10000])

In [140]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill,
                                  temporary_stats[0,column_integers[2]],
                                  loan_data_numeric[:,2])

In [141]:
loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000, 68616520,      938,     4679],
       [59432726,    15000,    15000, 68616520,      494,     1969],
       ...,
       [50415990,    10000,    10000, 68616520, 68616520,     2185],
       [46154151, 68616520,    10000,       16,      354,     3199],
       [66055249,    10000,    10000, 68616520,      309,      301]])

In [142]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

# loan_amnt, int_rate, installment, total_pymnt(replace the temp_fill in this case with temporary_max values)

In [143]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [144]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                      temporary_stats[2,column_integers[i]],
                                      loan_data_numeric[:,i])

In [145]:
loan_data_numeric[:,i]

array([9452, 4679, 1969, ..., 2185, 3199,  301])

In [146]:
loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000,       28,      938,     4679],
       [59432726,    15000,    15000,       28,      494,     1969],
       ...,
       [50415990,    10000,    10000,       28,     1372,     2185],
       [46154151,    35000,    10000,       16,      354,     3199],
       [66055249,    10000,    10000,       28,      309,      301]])

# Convert Dollar Amounts to Euros

# The Exchange Rates

In [147]:
EUR_USD = np.genfromtxt("EUR-USD.csv",delimiter=",",autostrip=True,skip_header = 1,usecols=3)

In [148]:
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [149]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [150]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [151]:
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [152]:
exchange_rate = loan_data_strings[:,0]

In [153]:
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

In [154]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [155]:
exchange_rate.shape

(10000,)

In [156]:
loan_data_numeric.shape

(10000, 6)

In [157]:
exchange_rate = np.reshape(exchange_rate,(10000,1))
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [158]:
loan_data_numeric

array([[48010226,    35000,    35000,       13,     1184,     9452],
       [57693261,    30000,    30000,       28,      938,     4679],
       [59432726,    15000,    15000,       28,      494,     1969],
       ...,
       [50415990,    10000,    10000,       28,     1372,     2185],
       [46154151,    35000,    10000,       16,      354,     3199],
       [66055249,    10000,    10000,       28,      309,      301]])

# Add last column of exchange_rate to loan_data_numeric

In [159]:
loan_data_numeric = np.hstack((loan_data_numeric,exchange_rate))

In [160]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.  ,     9452.  ,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.  ,     4679.  ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.  ,     1969.  ,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.  ,     2185.  ,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.  ,     3199.  ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.  ,      301.  ,        1.09]])

# Add exchange rate column to header

In [161]:
header_numeric = np.concatenate((header_numeric,np.array(['exchange_rate'])))

In [162]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

# From USD to EUR

In [163]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [164]:
column_dollar = np.array([1,2,4,5])

In [165]:
column_dollar

array([1, 2, 4, 5])

In [166]:
loan_data_numeric[:,[column_dollar]]

array([[[35000., 35000.,  1184.,  9452.]],

       [[30000., 30000.,   938.,  4679.]],

       [[15000., 15000.,   494.,  1969.]],

       ...,

       [[10000., 10000.,  1372.,  2185.]],

       [[35000., 10000.,   354.,  3199.]],

       [[10000., 10000.,   309.,   301.]]])

In [167]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [168]:
for i in column_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],(10000,1))))

In [169]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1080.26,     8623.82],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.34,     4231.76],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      438.88,     1749.3 ],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1222.49,     1946.9 ],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.51,     2878.27],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      282.61,      275.29]])

In [170]:
loan_data_numeric.shape

(10000, 11)

In [171]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1080.26,     8623.82],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.34,     4231.76],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      438.88,     1749.3 ],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1222.49,     1946.9 ],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.51,     2878.27],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      282.61,      275.29]])

In [172]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[column_dollar]])

In [173]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [174]:
header_numeric = np.concatenate((header_numeric,header_additional))

In [175]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [176]:
header_numeric[column_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[column_dollar]])

In [177]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [178]:
column_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [181]:
header_numeric = header_numeric[column_index_order]

In [182]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [183]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1080.26,     8623.82],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.34,     4231.76],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      438.88,     1749.3 ],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1222.49,     1946.9 ],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.51,     2878.27],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      282.61,      275.29]])

In [184]:
loan_data_numeric = loan_data_numeric[:,column_index_order]

In [185]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.  ,     8623.82,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.  ,     4231.76,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.  ,     1749.3 ,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.  ,     1946.9 ,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.  ,     2878.27,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.  ,      275.29,        1.09]])

# Interest Rate

In [186]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [187]:
loan_data_numeric[:,5]

array([13., 28., 28., ..., 28., 16., 28.])

In [190]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [191]:
loan_data_numeric[:,5]

array([0.13, 0.28, 0.28, ..., 0.28, 0.16, 0.28])

# Checkpoint 2 : Numeric

In [192]:
checkpoint_numeric = checkpoint("Checkpoint Numeric",header_numeric,loan_data_numeric)

In [194]:
checkpoint_numeric["header"]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [195]:
checkpoint_numeric["data"]

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.  ,     8623.82,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.  ,     4231.76,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.  ,     1749.3 ,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.  ,     1946.9 ,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.  ,     2878.27,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.  ,      275.29,        1.09]])

# Creating the complete Dataset

In [196]:
loan_data_strings.shape

(10000, 6)

In [197]:
loan_data_numeric.shape

(10000, 11)

In [201]:
np.hstack((checkpoint_numeric["data"],checkpoint_strings["data"]))

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [205]:
loan_data = np.hstack((checkpoint_numeric["data"],checkpoint_strings["data"]))

In [206]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [208]:
np.isnan(loan_data).sum()

0

In [210]:
header_full = np.concatenate((checkpoint_numeric["header"],checkpoint_strings["header"]))

In [211]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

# Sorting the new dataset

In [212]:
loan_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [215]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [216]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [217]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

# Storing the new dataset

In [219]:
loan_data = np.vstack((header_full,loan_data))

In [220]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [221]:
np.savetxt("loan-data-preprocessed.csv",loan_data,fmt="%s",delimiter=",")